// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenBoardAnim.Library;

#nullable disable

namespace OpenBoardAnim.Library.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260818121013_AddSceneTemplates")]
    partial class AddSceneTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("OpenBoardAnim.Library.GraphicEntity", b =>
                {
                    b.Property<int>("GraphicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SVGText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GraphicID");

                    b.ToTable("Graphics");
                });

            modelBuilder.Entity("OpenBoardAnim.Library.ProjectEntity", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LatestLaunchTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SceneCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("OpenBoardAnim.Library.SceneTemplateEntity", b =>
                {
                    b.Property<int>("SceneTemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SceneTemplateID");

                    b.ToTable("SceneTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
